name: Build Java Project  # Workflow name

on:
  push:
    branches:
      - main  # Runs when code is pushed to the 'main' branch
  pull_request:  # Runs when a pull request is created or updated
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest  # Runner (Linux machine)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Fetches the repository code

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Uses Eclipse Temurin JDK
          java-version: '17'  # Specifies Java version

      - name: Build Project with Maven
        run: mvn clean install  # Runs Maven build command
